TallerMotos/Controllers/ReservasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Collections.Generic;
using TallerMotos.Application.DTO;
using TallerMotos.Application.Services.Implementations;
using TallerMotos.Application.Services.Interfaces;
using TallerMotos.Web.Models;
using X.PagedList;

namespace TallerMotos.Web.Controllers
{
    public class ReservasController : Controller
    {
        private readonly IServiceReservas _serviceReservas;
        private readonly IServiceSucursales _serviceSucursales;
        private readonly IServiceServicios _serviceServicios;
        private readonly IServiceUsuarios _serviceUsuarios;
        private readonly IServiceHorarios _serviceHorarios;
        private readonly IServiceFacturas _serviceFacturas;

        public ReservasController(IServiceReservas serviceReservas, IServiceSucursales serviceSucursales, IServiceServicios serviceServicios, IServiceUsuarios serviceUsuarios, IServiceHorarios serviceHorarios, IServiceFacturas serviceFacturas)
        {
            _serviceReservas = serviceReservas;
            _serviceSucursales = serviceSucursales;
            _serviceServicios = serviceServicios;
            _serviceUsuarios = serviceUsuarios;
            _serviceHorarios = serviceHorarios;
            _serviceFacturas = serviceFacturas;
        }
        //public async Task<IActionResult> Index()
        //{
        //    var collection = await _serviceReservas.ListAsync();
        //    ViewData["Title"] = "Index";
        //    return View(collection);
        //}


        public async Task<IActionResult> Index(int id, string diaSeleccionado, int? page)
        {
            // Obtén las reservas por sucursal
            var collection = await _serviceReservas.ListBySucursalAsync(id);
            ViewBag.ListaUsuarios = await _serviceUsuarios.ListAsync();

            // Filtra por día si se ha seleccionado uno
            if (!string.IsNullOrEmpty(diaSeleccionado))
            {
                collection = collection.Where(r => r.Dia == diaSeleccionado).ToList();
            }

            // Guarda el id de la sucursal en ViewData
            ViewData["SucursalId"] = id;
            // Guarda los días de la semana en ViewBag para el combo box
            ViewBag.DiasDeLaSemana = new List<string> { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes" };

            ViewData["Title"] = "Index";
            return View(collection.ToPagedList(page ?? 1, 5));
        }



        public async Task<ActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }
                var reserva = await _serviceReservas.FindByIdAsync(id.Value);
                if (reserva == null)
                {
                    throw new Exception("Reservas no existente");
                }
                ViewData["SucursalId"] = reserva.IDSucursal;
                return View(reserva);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public async Task<ActionResult> DetailsProforma(int? id)
        {
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }
                var reserva = await _serviceReservas.FindByIdAsync(id.Value);
                if (reserva == null)
                {
                    throw new Exception("Reservas no existente");
                }
                ViewData["SucursalId"] = reserva.IDSucursal;
                return View(reserva);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [Authorize(Roles = "Cliente,Encargado")]
        public async Task<IActionResult> Create(int idsucursal)
        {
            var usuarios = await _serviceUsuarios.ListAsync();
            var usuariosDTO = usuarios.Select(u => new UsuariosDTO
            {
                ID = u.ID,
                Nombre = u.Nombre,
                Correo = u.Correo
            }).ToList();

            var servicios = await _serviceServicios.ListAsync();
            var serviciosDTO = servicios.Select(s => new ServiciosDTO
            {
                ID = s.ID,
                Nombre = s.Nombre,
                Tiempo = s.Tiempo
            }).ToList();

            // Obtener la sucursal por ID
            var sucursal = await _serviceSucursales.FindByIdAsync(idsucursal);

            // Pasar los datos necesarios al ViewBag
            ViewBag.ListaUsuarios = usuariosDTO;
            ViewBag.UsuariosJson = JsonConvert.SerializeObject(usuariosDTO);

            ViewBag.ListaServicios = serviciosDTO;
            ViewBag.ServiciosJson = JsonConvert.SerializeObject(serviciosDTO);

            // Pasar la sucursal al ViewBag
            ViewBag.ListaSucursales = sucursal;

            // Pasar el ID de la sucursal a ViewData para la redirección
            ViewData["SucursalId"] = idsucursal;

            // Obtener los días disponibles para la sucursal
            var diasDisponibles = await _serviceHorarios.GetDiasDisponiblesAsync(idsucursal);
            ViewBag.DiasDisponibles = new SelectList(diasDisponibles);

            ViewBag.ListaEstados = new List<SelectListItem>
            {
                new SelectListItem { Value = "Pendiente", Text = "Pendiente" },
                new SelectListItem { Value = "Confirmada", Text = "Confirmada" },
                new SelectListItem { Value = "Completada", Text = "Completada" },
                new SelectListItem { Value = "Cancelada", Text = "Cancelada" },
                new SelectListItem { Value = "Reprogramada", Text = "Reprogramada" },
                new SelectListItem { Value = "Proforma", Text = "Proforma" }
            };

            

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ReservasDTO dto)
        {
            FacturaDTO factura = new FacturaDTO();
            //Validación del formulario 
            if (!ModelState.IsValid)
            {
                //var sucursales = await _serviceSucursales.ListAsync();
                //ViewBag.ListaSucursales = new SelectList(sucursales, "ID", "Nombre");
                // Lee del ModelState todos los errores que 
                // vienen para el lado del server 
                string errors = string.Join("; ", ModelState.Values
                                   .SelectMany(x => x.Errors)
                                   .Select(x => x.ErrorMessage));
                ViewBag.ErrorMessage = errors;
                ViewBag.ListaSucursales = await _serviceSucursales.FindByIdAsync(dto.IDSucursal);

                //FacturaDTO factura = new FacturaDTO();
                

                return View();
            }

            //Proforma
            DetalleFacturaDTO detFactura = new DetalleFacturaDTO();
            ServiciosDTO servi=new ServiciosDTO();
            //  var  servicio= _serviceServicios.GetByIdAsync(dto.IDServicio);
            var servicio = await _serviceServicios.GetByIdAsync(dto.IDServicio);



            factura.Fecha = DateOnly.Parse(DateTime.Today.ToString("dd-MM-yyyy"));
            factura.IDSucursal = dto.IDSucursal;
            factura.IDUsuario = dto.IDUsuario;
            factura.Estado = "Proforma";
            factura.SubTotal = servicio.Precio;
            factura.Impuesto = "" + (Convert.ToDouble(factura.SubTotal) * 0.13);
            factura.Total = "" + (Convert.ToDouble(factura.SubTotal) + Convert.ToDouble(factura.Impuesto));

            var nextReceiptNumber = await _serviceFacturas.GetNextNumberOrden();
          //  var serv = dto.IdservicioNavigation.Nombre;
            detFactura.IDFactura = nextReceiptNumber;
            detFactura.Codigo = "" + dto.IDServicio;
            detFactura.Nombre = servicio.Nombre;//"servicio";
            detFactura.Cantidad = "" + 1;
            detFactura.Precio = servicio.Precio;
            detFactura.Impuesto = "" + (Convert.ToDouble(detFactura.Precio) * 0.13);
            detFactura.SubTotal = "" + (Convert.ToDouble(detFactura.Cantidad) * Convert.ToDouble(detFactura.Precio));
            detFactura.Total = "" + (Convert.ToDouble(detFactura.SubTotal) + Convert.ToDouble(detFactura.Impuesto));

            List<DetalleFacturaDTO> lista = new List<DetalleFacturaDTO>();

            lista.Add(detFactura);

            factura.DetalleFactura = lista;

            //Crear 
            await _serviceReservas.AddAsync(dto);
            await _serviceFacturas.AddAsync(factura);
            return RedirectToAction("Index", new { idSucursal = dto.IDSucursal });
        }

        [HttpGet]
        public IActionResult GetHorasDisponibles(string dia)
        {
            if (string.IsNullOrEmpty(dia))
            {
                return Json(new { horas = new List<string>() });
            }

            var horas = _serviceHorarios.GetHorasDisponibles(dia);

            return Json(new { horas });
        }



        //[HttpGet]
        //public async Task<JsonResult> GetServicioTiempo(int id)
        //{
        //    var servicio = await _serviceServicios.GetByIdAsync(id);
        //    if (servicio != null)
        //    {
        //        return Json(new { tiempo = servicio.Tiempo });
        //    }
        //    return Json(new { tiempo = "" });
        //}

        public IActionResult ErrorHandler(string messageJson)
        {
            var errorMessages = JsonConvert.
                DeserializeObject<ErrorMiddlewareViewModel>(messageJson);
            ViewBag.ErrorMessages = errorMessages;
            return View("ErrorHandler");
        }
    }
}

TallerMotos/Views/Reservas/Create.cshtml
@using Newtonsoft.Json
@model TallerMotos.Application.DTO.ReservasDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Reservas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
            }

            @* <div class="form-group">
                ¿Qué 
                <label asp-for="IdservicioNavigation" class="control-label"></label> desea elegir?
                @*<input asp-for="IdAutor" class="form-control" />*@
               @* @Html.DropDownListFor(m => m.IDServicio,
                         new SelectList(ViewBag.ListaServicios, "ID", "Nombre"),
                         "Seleccione un Servicio",
                         new { @class = "form-select" }
                         )

                <span asp-validation-for="IDServicio" class="text-danger"></span>
            </div> *@

            <div class="form-group">
                ¿Qué 
                <label asp-for="IdservicioNavigation" class="control-label"></label> desea recibir?
                @Html.DropDownListFor(model => model.IDServicio,
                         new SelectList(ViewBag.ListaServicios, "ID", "Nombre"),
                         "Seleccione un Servicio",
                         new { @class = "form-select", id = "ServicioDropdown" })
                <span asp-validation-for="IDServicio" class="text-danger"></span>
            </div>

            <div class="form-group">
                <h6 id="ServicioInfo"></h6>
            </div>

            <div class="form-group">
                <label asp-for="IdsucursalNavigation" class="control-label"></label>
                @Html.HiddenFor(model => model.IDSucursal)
                <input class="form-control" value="@ViewBag.ListaSucursales.Nombre" disabled />
                <span asp-validation-for="IDSucursal" class="text-danger"></span>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IdusuarioNavigation, "Usuario", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DropDownListFor(m => m.IDUsuario,
                         new SelectList(ViewBag.ListaUsuarios, "ID", "Nombre"),
                         "Seleccione un Usuario",
                         new { @class = "form-select", id = "UsuarioDropdown" })
                <span asp-validation-for="IDUsuario" class="text-danger"></span>
            </div>

            <div class="form-group">
                <h6 id="UsuarioInfo"></h6>
            </div>

            @* <div class="form-group">
                <label asp-for="Dia" class="control-label"></label>
                @Html.DropDownListFor(m => m.Dia, (SelectList)ViewBag.DiasDisponibles, "Seleccione un día", new { @class = "form-control" })
                <span asp-validation-for="Dia" class="text-danger"></span>
            </div> *@

            <div class="form-group">
                ¿Qué 
                <label asp-for="Dia" class="control-label"></label> desea reservar la cita?
                @Html.DropDownListFor(m => m.Dia, (SelectList)ViewBag.DiasDisponibles, "Seleccione un día", new { @class = "form-control", id = "diaCombo" })
                <span asp-validation-for="Dia" class="text-danger"></span>
            </div>

            <div class="form-group">
                ¿Qué 
                <label asp-for="Hora" class="control-label"></label> desea seleccionar?
                <select asp-for="Hora" class="form-control" id="horaCombo">
                    <option value="">Seleccione una hora</option>
                </select>
                <span asp-validation-for="Hora" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                @Html.DropDownListFor(m => m.Estado, (IEnumerable<SelectListItem>)ViewBag.ListaEstados, "Seleccione un Estado", new { @class = "form-control" })
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>

            @* <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div> *@

            
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" /> |
                <a class="btn btn-info" asp-action="Index" asp-route-id="@ViewData["SucursalId"]">Regresar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            // Definir funciones para mostrar mensajes
            function showSuccessMessage(title, text) {
                Swal.fire({
                    icon: 'success',
                    title: title,
                    text: text,
                    showConfirmButton: false,
                    timer: 5000 // Tiempo en milisegundos que el mensaje estará visible
                });
            }

            function showErrorMessage(title, text) {
                Swal.fire({
                    icon: 'error',
                    title: title,
                    text: text,
                    showConfirmButton: true
                });
            }

            // Manejador para el envío del formulario
            $('form').on('submit', function (e) {
                e.preventDefault(); // Prevenir el envío del formulario para manejarlo con AJAX

                var $form = $(this);
                $.ajax({
                    url: $form.attr('action'),
                    type: 'POST',
                    data: $form.serialize(),
                    success: function (response) {
                        showSuccessMessage('Reserva creada', 'La reserva se ha creado exitosamente.');
                        setTimeout(function () {
                            window.location.href = '@Url.Action("Index", "Reservas")'; // Redirigir a otra página
                        }, 2000); // Espera de 2 segundos para permitir que el mensaje se muestre antes de redirigir
                    },
                    error: function (xhr, status, error) {
                        showErrorMessage('Error', 'No se pudo crear la reserva.');
                    }
                });
            });

            // Código existente para dropdowns y AJAX
            $('#diaCombo').change(function () {
                var selectedDia = $(this).val();

                $.ajax({
                    url: '@Url.Action("GetHorasDisponibles", "Reservas")',
                    type: 'GET',
                    data: { dia: selectedDia },
                    success: function (data) {
                        var $horaCombo = $('#horaCombo');
                        $horaCombo.empty(); // Clear previous options
                        $horaCombo.append('<option value="">Seleccione una hora</option>'); // Add default option

                        $.each(data.horas, function (index, hora) {
                            $horaCombo.append($('<option>').text(hora).attr('value', hora));
                        });

                        // Puedes agregar aquí otro tipo de mensajes si es necesario, pero no de éxito
                        // showSuccessMessage('Horas actualizadas', 'Las horas disponibles se han actualizado.');
                    },
                    error: function (xhr, status, error) {
                        showErrorMessage('Error', 'No se pudieron obtener las horas disponibles.');
                    }
                });
            });

            // Código para actualizar la información del usuario y servicio
            var usuarios = @Html.Raw(ViewBag.UsuariosJson);
            var servicios = @Html.Raw(ViewBag.ServiciosJson);

            function updateUsuarioInfo() {
                var selectedUserId = $('#UsuarioDropdown').val();
                var selectedUser = usuarios.find(u => u.ID == selectedUserId);

                if (selectedUser) {
                    $('#UsuarioInfo').text(`Nombre: ${selectedUser.Nombre}, Correo: ${selectedUser.Correo}`);
                } else {
                    $('#UsuarioInfo').text('');
                }
            }

            function updateServicioInfo() {
                var selectedServicioId = $('#ServicioDropdown').val();
                var selectedServicio = servicios.find(s => s.ID == selectedServicioId);

                if (selectedServicio) {
                    $('#ServicioInfo').text(`Nombre: ${selectedServicio.Nombre}, Tiempo: ${selectedServicio.Tiempo} horas`);
                } else {
                    $('#ServicioInfo').text('');
                }
            }

            $('#UsuarioDropdown').change(updateUsuarioInfo);
            $('#ServicioDropdown').change(updateServicioInfo);

            updateUsuarioInfo();
            updateServicioInfo();
        });
    </script>
}

TallerMotos/Views/Reservas/Details.cshtml
@model TallerMotos.Application.DTO.ReservasDTO

@{
    ViewData["Title"] = "Detalle";
}

<h1>Detalle</h1>

<div>
    <h4>Reservas</h4>
    <hr />
    <div class="card flex-row text-right" style="width:60%; margin:0 auto;">
        <img style="max-height:100px;"
             role="img"
             src="~/imagenes/reservalogo.png" 
             alt="Proximamente" />

        <div class="card-body">
            <h5 class="card-title">Reserva: @Html.DisplayFor(model => model.ID)</h5>
            <p class="card-text"><b>@Html.DisplayNameFor(model => model.IdservicioNavigation):</b>  @Html.DisplayFor(model => model.IdservicioNavigation.Nombre)</p>
            <p class="card-text"><b>@Html.DisplayNameFor(model => model.IdsucursalNavigation):</b>  @Html.DisplayFor(model => model.IdsucursalNavigation.Nombre)</p>
            <p class="card-text"><b>@Html.DisplayNameFor(model => model.IdusuarioNavigation):</b>   @Html.DisplayFor(model => model.IdusuarioNavigation.Nombre)</p>
            <p class="card-text"><b>@Html.DisplayNameFor(model => model.Dia):</b>  @Html.DisplayFor(model => model.Dia)</p>
            <p class="card-text"><b>@Html.DisplayNameFor(model => model.Hora):</b>  @Html.DisplayFor(model => model.Hora)</p>
            <p class="card-text"><b>@Html.DisplayNameFor(model => model.Estado):</b>  @Html.DisplayFor(model => model.Estado)</p>
            

        </div>

        <div class="d-flex align-items-end">
            <a class="btn btn-primary" asp-action="Index" asp-route-id="@ViewData["SucursalId"]">Regresar</a>
        </div>
    </div>

</div>
<div>
</div>

TallerMotos/Views/Reservas/DetailsProforma.cshtml
@model TallerMotos.Application.DTO.ReservasDTO

@{
    ViewData["Title"] = "Detalle Proforma";
    <link rel="stylesheet" href="~/css/EstiloFact.css" asp-append-version="true" />
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
        }

        .footer {
            text-align: center;
            margin-bottom: 20px;
        }

        .header {
            display: flex;
            justify-content: space-between;
            margin-bottom 20px;
        }

            .header h2 {
                margin-top: 20px;
                text-align: right;
                display: flex;
                width: 60%;
            }

            .header img {
                text-align: center;
                max-width: 250px;
                display: flex;
                width: 48%;
            }

        .Enc {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }

        .company-details, .customer-details {
            margin-bottom: 20px;
            width: 48%;
        }

            .company-details h2, .customer-details h2 {
                margin: 0 0 10px;
                width: 48%;
            }

        .details {
            width: 100%;
            margin-bottom: 20px;
            border-collapse: collapse;
        }

            .details th, .details td {
                border: 1px solid #ccc;
                padding: 10px;
                text-align: left;
            }

            .details th {
                background-color: black;
                color: white;
            }

        .total {
            text-align: right;
            margin-top: 20px;
        }

            .total h3 {
                margin: 0;
            }

        .btn-primary {
            background-color: #007bff;
            border: none;
            color: #fff;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
        }

            .btn-primary:hover {
                background-color: #0056b3;
            }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <img src="~/imagenes/logo2SF.png" alt="Logo de la empresa">
            <h2>Reserva #: @Html.DisplayFor(model => model.ID)<br />Fecha: @DateTime.Now.ToString("dd/MM/yyyy")</h2>
        </div>

        <div class="Enc">
            <div class="company-details">
                <h2>Detalles de la Sucursal</h2>
                <p>Sucursal: @Html.DisplayFor(model => model.IdsucursalNavigation.Nombre)</p>
                <p>Teléfono: @Html.DisplayFor(model => model.IdsucursalNavigation.Telefono)</p>
                <p>Email: @Html.DisplayFor(model => model.IdsucursalNavigation.Correo)</p>
            </div>
            <div class="customer-details">
                <h2>Detalles del Cliente</h2>
                <p>Nombre del Cliente: @Html.DisplayFor(model => model.IdusuarioNavigation.Nombre)</p>
                <p>Identificación: @Html.DisplayFor(model => model.IdusuarioNavigation.ID)</p>
            </div>
        </div>

        <table class="details">
            <thead>
                <tr>
                    <th>Servicio</th>
                    <th>Tiempo de Servicio</th>
                    <th>Cilindraje para el Servicio</th>
                    <th>Día</th>
                    <th>Hora</th>
                    <th>Estado</th>
                    <th>Precio</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Html.DisplayFor(model => model.IdservicioNavigation.Nombre)</td>
                    <td>@Html.DisplayFor(model => model.IdservicioNavigation.Tiempo) horas</td>
                    <td>@Html.DisplayFor(model => model.IdservicioNavigation.Cilindrada)</td>
                    <td>@Html.DisplayFor(model => model.Dia)</td>
                    <td>@Html.DisplayFor(model => model.Hora)</td>
                    <td>@Html.DisplayFor(model => model.Estado)</td>
                    <td>₡@Html.DisplayFor(model => model.IdservicioNavigation.Precio)</td>
                </tr>
            </tbody>
        </table>

        <div class="total">
            <h4>Precio: ₡@Html.DisplayFor(model => model.IdservicioNavigation.Precio)</h4>
        </div>

        <div class="footer">
            <p>Gracias por su compra</p>
            <a class="btn btn-primary" asp-action="Index" asp-route-id="@ViewData["SucursalId"]">Regresar</a>
        </div>
    </div>
</body>
</html>