TallerMotos/Controllers/HorariosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using TallerMotos.Application.DTO;
using TallerMotos.Application.Services.Interfaces;
using TallerMotos.Web.Models;
using X.PagedList;

namespace TallerMotos.Web.Controllers
{
    public class HorariosController : Controller
    {
        private readonly IServiceHorarios _serviceHorarios;
        private readonly IServiceSucursales _serviceSucursales;

        public HorariosController(IServiceHorarios serviceHorarios, IServiceSucursales serviceSucursales)
        {
            _serviceHorarios = serviceHorarios;
            _serviceSucursales = serviceSucursales;
        }
        //public async Task<IActionResult> Index()
        //{
        //    var collection = await _serviceHorarios.ListAsync();
        //    ViewData["Title"] = "Index";
        //    return View(collection);
        //}

        public async Task<ActionResult> Index(int? page)
        {
            var collection = await _serviceHorarios.ListAsync();
            //Cantidad de elementos por página
            return View(collection.ToPagedList(page ?? 1, 5));
        }

        public async Task<ActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }
                var @object = await _serviceHorarios.FindByIdAsync(id.Value);
                if (@object == null)
                {
                    throw new Exception("Horarios no existente");
                }
                return View(@object);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public IActionResult ErrorHandler(string messageJson)
        {
            var errorMessages = JsonConvert.
                DeserializeObject<ErrorMiddlewareViewModel>(messageJson);
            ViewBag.ErrorMessages = errorMessages;
            return View("ErrorHandler");
        }


        //[HttpGet]
        public async Task<ActionResult> Create()
        {
            //var sucursales = await _serviceSucursales.ListAsync();
            ViewBag.ListaSucursales = await _serviceSucursales.ListAsync(); //new SelectList(sucursales, "ID", "Nombre");

            ViewBag.DiasDeLaSemana = new SelectList(new List<string>
            {
                "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
            });
            return View();
        }



        // POST: HorariosController/Create 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(HorariosDTO dto)
        {
            //Validación del formulario 
            if (!ModelState.IsValid)
            {
                //var sucursales = await _serviceSucursales.ListAsync();
                //ViewBag.ListaSucursales = new SelectList(sucursales, "ID", "Nombre");
                // Lee del ModelState todos los errores que 
                // vienen para el lado del server 
                string errors = string.Join("; ", ModelState.Values
                                   .SelectMany(x => x.Errors)
                                   .Select(x => x.ErrorMessage));
                ViewBag.ErrorMessage = errors;
                ViewBag.DiasDeLaSemana = new SelectList(new List<string>
                {
                    "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
                });

                return View();
            }
            //Crear 
            await _serviceHorarios.AddAsync(dto);
            return RedirectToAction("Index");
        }

        //[HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            ViewBag.ListaSucursales = await _serviceSucursales.ListAsync();

            var HorariosDTO = await _serviceHorarios.GetByIdAsync(id);

            if (HorariosDTO == null)
            {
                return NotFound();
            }
            ViewBag.DiasDeLaSemana = new SelectList(new List<string>
            {
                "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
            });
            return View(HorariosDTO);
        }

        // POST: HorariosController/Edit/5 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, HorariosDTO dto)
        {
            if (!ModelState.IsValid)
            {
                // Lee del ModelState todos los errores que 
                // vienen para el lado del server 
                string errors = string.Join("; ", ModelState.Values
                                   .SelectMany(x => x.Errors)
                                   .Select(x => x.ErrorMessage));
                ViewBag.ErrorMessage = errors;

                return View();
            }
            else
            {
                //Actualizar 
                await _serviceHorarios.UpdateAsync(id, dto);
                return RedirectToAction("Index");
            }
        }

    }
}

TallerMotos/Views/Horarios/Create.cshtml
@model TallerMotos.Application.DTO.HorariosDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Horarios</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="IDSucursal" class="control-label"></label>
                @*<input asp-for="IdAutor" class="form-control" />*@
                @Html.DropDownListFor(m => m.IDSucursal,
                         new SelectList(ViewBag.ListaSucursales, "ID", "Nombre"),
                         "Seleccione una Sucursal",
                         new { @class = "form-select" }
                         )
                
                <span asp-validation-for="IDSucursal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dia" class="control-label"></label>
                <select asp-for="Dia" class="form-control" asp-items="ViewBag.DiasDeLaSemana">
                    <option value="">Seleccione un día</option>
                </select>
                <span asp-validation-for="Dia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hora" class="control-label"></label>
                <input asp-for="Hora" class="form-control" />
                <span asp-validation-for="Hora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <select asp-for="Estado" class="form-control">
                    <option value="">Seleccione un estado</option>
                    <option value="Activo">Activo</option>
                    <option value="Bloqueado">Bloqueado</option>
                </select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" /> |
                <a class="btn btn-info" asp-action="TablaSucursales">Regresar</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TallerMotos/Views/Horarios/Details.cshtml
@model TallerMotos.Application.DTO.HorariosDTO

@{
    ViewData["Title"] = "Detalle";

}

<h1>Detalle</h1>

<div>
    <h4>Horarios</h4>
    <hr />
    <div class="card flex-row text-right" style="width:60%; margin:0 auto;">
        <img style="max-height:273px;"
             role="img"
        <img src="~/imagenes/logoMoto.jpeg" alt="Logo de la empresa">

        <div class="card-body">
            <h5 class="card-title">ID: @Html.DisplayFor(model => model.ID)</h5>
            <p class="card-text"><b>@Html.DisplayNameFor(model => model.IdsucursalesNavigation):</b>  @Html.DisplayFor(model => model.IdsucursalesNavigation.Nombre)</p>
            <p class="card-text"><b>@Html.DisplayNameFor(model => model.Dia):</b>   @Html.DisplayFor(model => model.Dia)</p>
            <p class="card-text"><b>@Html.DisplayNameFor(model => model.Hora):</b>  @Html.DisplayFor(model => model.Hora)</p>
            <p class="card-text"><b>@Html.DisplayNameFor(model => model.Estado):</b>  @Html.DisplayFor(model => model.Estado)</p>

        </div>
        <div class="d-flex align-items-end">
            <a class="btn btn-primary" asp-action="Index">Regresar</a>
        </div>
    </div>

</div>
<div>
</div>

TallerMotos/Views/Horarios/Edit.cshtml
@model TallerMotos.Application.DTO.HorariosDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Horarios</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IDSucursal" class="control-label"></label>
                @*<input asp-for="IdAutor" class="form-control" />*@
                @Html.DropDownListFor(m => m.IDSucursal,
                         new SelectList(ViewBag.ListaSucursales, "ID", "Nombre"),
                         "Seleccione una Sucursal",
                         new { @class = "form-select" }
                         )

                <span asp-validation-for="IDSucursal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dia" class="control-label"></label>
                <select asp-for="Dia" class="form-control" asp-items="ViewBag.DiasDeLaSemana">
                    <option value="">Seleccione un día</option>
                </select>
                <span asp-validation-for="Dia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hora" class="control-label"></label>
                <input asp-for="Hora" class="form-control" />
                <span asp-validation-for="Hora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <select asp-for="Estado" class="form-control">
                    <option value="">Seleccione un estado</option>
                    <option value="Activo">Activo</option>
                    <option value="Bloqueado">Bloqueado</option>
                </select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" /> |
                <a class="btn btn-info" asp-action="Index">Regresar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TallerMotos/Views/Horarios/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model IEnumerable<TallerMotos.Application.DTO.HorariosDTO>

@{

    Layout = "_Layout";
}

<h1>Horarios</h1>

<p>
    <a class="btn btn-primary" asp-controller="Horarios" asp-action="Create">Crear</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IDSucursal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdsucursalesNavigation.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.ID }, new { @class = "btn btn-success" }) |
                    <a asp-controller="Horarios" asp-action="Details" asp-route-id="@item.ID" class="btn btn-info">Detalle</a> |
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" })

                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="5">
                <div class="btn-toolbar d-flex justify-content-end" role="toolbar">
                    <div class="btn-group" role="group">
                        @Html.PagedListPager((IPagedList)Model, page =>
                                 Url.Action("Index", new { page }), new
                                 PagedListRenderOptions
                        {
                            Display = PagedListDisplayMode.Always,
                            MaximumPageNumbersToDisplay = 5,
                            LiElementClasses = new String[] { "page-item" },
                            PageClasses = new String[] { "page-link" }
                        }
                                 )
                    </div>
                </div>
            </td>
        </tr>
    </tfoot>
</table>