TallerMotos/Controllers/AgendaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TallerMotos.Application.Services.Interfaces;

namespace TallerMotos.Web.Controllers
{
    public class AgendaController : Controller
    {
        private readonly IServiceReservas _serviceReservas;
        private static readonly Dictionary<string, DayOfWeek> DiasEnEspanol = new Dictionary<string, DayOfWeek>
{
    { "Lunes", DayOfWeek.Monday },
    { "Martes", DayOfWeek.Tuesday },
    { "Miércoles", DayOfWeek.Wednesday },
    { "Jueves", DayOfWeek.Thursday },
    { "Viernes", DayOfWeek.Friday },
    { "Sábado", DayOfWeek.Saturday },
    { "Domingo", DayOfWeek.Sunday }
};

        public AgendaController(IServiceReservas serviceReservas)
        {
            _serviceReservas = serviceReservas;
        }

        public async Task<IActionResult> Index()
        {
            var reservas = await _serviceReservas.ListAsync(); // Obtener reservas del servicio



            var eventos = reservas.Select(r =>
            {
                TimeSpan hora;
                if (!TimeSpan.TryParse(r.Hora, out hora))
                {
                    // Manejo de error si el valor de la hora no es válido
                    hora = TimeSpan.Zero; // o asigna un valor por defecto adecuado
                }

                return new
                {
                    title = r.IdusuarioNavigation.Nombre + "-" + r.Estado, // Mostrar el estado como título del evento

                    // Convertir el string de la hora a un TimeSpan o DateTime
                    start = ObtenerFechaHora(r.Dia, hora),  // Combina día y hora en formato ISO
                    end = ObtenerFechaHora(r.Dia, hora.Add(TimeSpan.FromHours(1))), // Duración de una hora

                    description = r.Estado, // Descripción del evento
                    backgroundColor = ObtenerColorEstado(r.Estado) // Cambiar color según estado
                };
            }).ToList();

            ViewBag.Eventos = Newtonsoft.Json.JsonConvert.SerializeObject(eventos);

            return View();
        }

        private string ObtenerFechaHora(string dia, TimeSpan hora)
        {
            if (string.IsNullOrEmpty(dia))
            {
                throw new ArgumentException("El día no puede ser nulo o vacío.");
            }

            DateTime now = DateTime.Now;
            if (DiasEnEspanol.TryGetValue(dia, out DayOfWeek diaDeLaSemana))
            {
                int diasDiferencia = (int)diaDeLaSemana - (int)now.DayOfWeek;
                if (diasDiferencia < 0)
                {
                    diasDiferencia += 7; // Ajustar para que siempre se obtenga el próximo día de la semana
                }
                DateTime fecha = now.AddDays(diasDiferencia).Date + hora;

                return fecha.ToString("yyyy-MM-ddTHH:mm:ss");
            }
            else
            {
                throw new ArgumentException($"El día {dia} no es válido.");
            }
        }

        private string ObtenerColorEstado(string estado)
        {
            switch (estado)
            {
                case "Confirmada": return "green";
                case "Pendiente": return "orange";
                case "Cancelada": return "red";
                default: return "blue";
            }
        }
    }
}

TallerMotos/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace TallerMotos.Web.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TallerMotos/Controllers/FacturaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TallerMotos.Application.DTO;
using TallerMotos.Application.Services.Interfaces;
using TallerMotos.Infraestructure.Models;
using TallerMotos.Web.Models;
using X.PagedList;
using JsonSerializer = System.Text.Json.JsonSerializer;



namespace TallerMotos.Web.Controllers
{
    [Authorize]
    public class FacturaController : Controller
    {
        private readonly IServiceFacturas _serviceFactura;
        private readonly IServiceProductos _serviceProductos;
        private readonly IServiceSucursales _serviceSucursales;
        private readonly IServiceServicios _serviceServicios;
        private readonly IServiceUsuarios _serviceUsuarios;
        public FacturaController(IServiceFacturas serviceFactura, IServiceProductos serviceProductos, IServiceSucursales serviceSucursales, IServiceServicios serviceServicios, IServiceUsuarios serviceUsuarios)
        {
            _serviceFactura = serviceFactura;
            _serviceProductos = serviceProductos;
            _serviceSucursales = serviceSucursales;
            _serviceServicios = serviceServicios;
            _serviceUsuarios = serviceUsuarios;
        }
        public async Task<IActionResult> Index(int? page, DateOnly? fecha)
        {
            var collection = await _serviceFactura.ListAsync();
            ViewBag.ListaUsuarios = await _serviceUsuarios.ListAsync();

            if (fecha.HasValue)
            {
                collection = collection.Where(f => f.Fecha == fecha.Value).ToList();
                ViewData["fecha"] = fecha.Value.ToString("yyyy-MM-dd");
            }

            ViewData["Title"] = "Index";
            return View(collection.ToPagedList(page ?? 1, 5));
        }
        public IActionResult ErrorHandler(string messageJson)
        {
            var errorMessages = JsonConvert.
                DeserializeObject<ErrorMiddlewareViewModel>(messageJson);
            ViewBag.ErrorMessages = errorMessages;
            return View("ErrorHandler");
        }
        public async Task<ActionResult> Create()
        {
            // var ListaCategorias = await _serviceCategoria.ListAsync();
            // ViewBag.ListaCategorias = new MultiSelectList(ListaCategorias, "IdCategoria", "Nombre");
            ViewBag.ListaProductos = await _serviceProductos.ListAsync();
            ViewBag.ListaSucursales = await _serviceSucursales.ListAsync();
            ViewBag.ListaServicios = await _serviceServicios.ListAsync();
            ViewBag.ListaUsuarios = await _serviceUsuarios.ListAsync();
            ViewBag.ListaEstados = new List<string> { "Proforma", "Cancelada", "Pendiente", "Anulada" };
            //Número de factura siguiente posible
            var nextReceiptNumber = await _serviceFactura.GetNextNumberOrden();
            ViewBag.CurrentReceipt = nextReceiptNumber;
            TempData["CartShopping"] = null;
            TempData.Keep();

            return View();
        }

        //[Authorize(Roles = "Administrador,Encargado")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(FacturaDTO dto)
        {

            string json;

            var cliente = await _serviceUsuarios.FindByIdAsync(dto.IDUsuario);

            if (cliente == null)
            {
                TempData.Keep();
                return BadRequest("Cliente No existe");
            }

            if (ModelState.IsValid)
            {
                string errors = string.Join("; ", ModelState.Values
                    .SelectMany(x => x.Errors)
                    .Select(x => x.ErrorMessage));
                ViewBag.ErrorMessage = errors;
                return View();
            }
            json = (string)TempData["CartShopping"]!;

            if (string.IsNullOrEmpty(json))
            {
                return BadRequest("No hay datos por facturar");
            }
            var lista = System.Text.Json.JsonSerializer.Deserialize<List<DetalleFacturaDTO>>(json!)!;
            //Agregar datos faltantes a la orden
            dto.ID = 0;
            //dto.IDUsuario = 2;
            //dto.IDSucursal = 3;
            //dto.Estado = "Proforma";
            dto.Fecha = DateOnly.Parse(DateTime.Today.ToString("dd-MM-yyyy"));
            dto.DetalleFactura = lista;
            dto.Total = "" + dto.DetalleFactura.Sum(p => Convert.ToDecimal(p.Total));
            dto.Impuesto = "" + dto.DetalleFactura.Sum(p => Convert.ToDecimal(p.Impuesto));
            dto.SubTotal = "" + dto.DetalleFactura.Sum(p => Convert.ToDecimal(p.SubTotal));

            await _serviceFactura.AddAsync(dto);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddProducto(int id, int cantidad)
        {

            DetalleFacturaDTO detalle = new DetalleFacturaDTO();
            List<DetalleFacturaDTO> lista = new List<DetalleFacturaDTO>();
            string json = "";

            var Producto = await _serviceProductos.FindByIdAsync(id);
            DetalleFacturaDTO item = new DetalleFacturaDTO();
            //Cantidad de item a guardar
            detalle.Cantidad = "" + cantidad;
            if (TempData["CartShopping"] != null)
            {
                json = (string)TempData["CartShopping"]!;
                lista = JsonSerializer.Deserialize<List<DetalleFacturaDTO>>(json!)!;
                //Buscar si existe el Libro en la compra
                item = lista.FirstOrDefault(o => int.Parse(o.Codigo) == id);
                if (item != null)
                {
                    detalle.Cantidad = "" + (int.Parse(detalle.Cantidad) + cantidad);

                }
            }
            // Validar que la cantidad en stock sea suficiente a la solicitada
            //if (detalle.Cantidad > Producto.Cantidad)
            //{
            //    return BadRequest("No hay inventario suficiente!");
            //}

            if (item != null && item.Cantidad != null)
            {
                //Actualizar cantidad de libro existente
                item.Cantidad = "" + (int.Parse(item.Cantidad) + cantidad);
                item.SubTotal = "" + int.Parse(item.Cantidad) * Convert.ToDecimal(Producto.Precio);
            }
            else
            {
                detalle.IDFactura = 0;
                detalle.Total = "0";
                detalle.Impuesto = "0";
                detalle.Codigo = "" + Producto.ID;
                detalle.Nombre = Producto.Nombre;
                detalle.Cantidad = "" + cantidad;
                detalle.Precio = Producto.Precio;
                var precio = Convert.ToDecimal(Producto.Precio);
                var cant = cantidad;
                var sub = (precio * cant);
                //Falta impuesto
                detalle.SubTotal = "" + sub; //""+(int.Parse(detalle.Precio) * int.Parse(detalle.Cantidad));
                detalle.Impuesto = "" + (Convert.ToDecimal(detalle.SubTotal) * Convert.ToDecimal(0.13));
                detalle.Total = "" + (Convert.ToDecimal(detalle.Impuesto) + Convert.ToDecimal(detalle.SubTotal));
                //Agregar al carrito de compras
                lista.Add(detalle);
            }
            json = JsonSerializer.Serialize(lista);
            TempData["CartShopping"] = json;




            TempData.Keep();
            return PartialView("_DetailFactura", lista);
        }

        public async Task<IActionResult> AddServicio(int id)
        {
            // Inicializar el objeto y lista
            DetalleFacturaDTO detalle = new DetalleFacturaDTO();
            List<DetalleFacturaDTO> lista = new List<DetalleFacturaDTO>();
            string json = "";

            // Obtener el servicio basado en el ID
            var Servicios = await _serviceServicios.FindByIdAsync(id);

            // Verificar si hay un carrito de compras en TempData
            if (TempData["CartShopping"] != null)
            {
                json = (string)TempData["CartShopping"];
                lista = JsonSerializer.Deserialize<List<DetalleFacturaDTO>>(json) ?? new List<DetalleFacturaDTO>();

                // Buscar el item en la lista
                var item = lista.FirstOrDefault(o => int.Parse(o.Codigo) == id);

                if (item != null)
                {
                    // Actualizar cantidad y subtotal si el servicio ya está en la lista
                    item.Cantidad = "" + (Convert.ToInt32(item.Cantidad) + 1); // Suponiendo cantidad 1
                    item.SubTotal = "" + (Convert.ToDecimal(item.Cantidad) * Convert.ToDecimal(Servicios.Precio));
                }
                else
                {
                    // Agregar nuevo servicio a la lista
                    detalle.IDFactura = 0;
                    detalle.Total = "0";
                    detalle.Impuesto = "0";
                    detalle.Codigo = "" + Servicios.ID;
                    detalle.Nombre = Servicios.Nombre;
                    detalle.Precio = Servicios.Precio;

                    // Suponiendo cantidad 1
                    var precio = Convert.ToDecimal(Servicios.Precio);
                    var cant = 1;
                    var sub = precio * cant;

                    detalle.SubTotal = "" + sub;
                    detalle.Impuesto = "" + (sub * 0.13m); // Asumiendo impuesto del 13%
                    detalle.Total = "" + (Convert.ToDecimal(detalle.Impuesto) + sub);

                    // Agregar al carrito de compras
                    lista.Add(detalle);
                }
            }
            else
            {
                // Si no hay carrito de compras, inicializar con un nuevo carrito
                detalle.IDFactura = 0;
                detalle.Total = "0";
                detalle.Impuesto = "0";
                detalle.Codigo = "" + Servicios.ID;
                detalle.Nombre = Servicios.Nombre;
                detalle.Precio = Servicios.Precio;

TallerMotos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @* https://bootswatch.com/ *@
    <link href="~/css/bootstrap-superhero.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TallerMotos.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    @*https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css*@

    <style>
        /* Estilo para el menú lateral fijo */
        .fixed-sidebar {
            position: fixed;
            top: 0;
            left: 0;
            width: 200px; /* Ajusta el ancho del menú lateral */
            height: 100%;
            z-index: 1000; /* Asegura que el menú esté encima del contenido */
            overflow-y: auto; /* Añade scroll si el contenido es más grande que la pantalla */
            background-color: #000; /* Color de fondo del menú */
        }

        /* Ajusta el contenido principal para no quedar debajo del menú lateral */
        .content-area {
            margin-left: 200px; /* Ajusta este margen según el ancho del menú */
            padding-left: 20px;
            padding-right: 20px;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Menú lateral fijo -->
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-black fixed-sidebar">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="@Url.Action("Index", "Home")" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <!-- <i class="bi bi-book"></i> -->
                        <span class="fs-5 d-none d-sm-inline">MS BEICHA</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li>
                            <a href="#submenuMantenimiento" data-bs-toggle="collapse" class="nav-link text-white px-0 align-middle">
                                <i class="fs-4 bi-wrench"></i> <span class="ms-1 d-none d-sm-inline">Mantenimientos</span>
                            </a>
                            <ul class="collapse show nav flex-column ms-1" id="submenuMantenimiento" data-bs-parent="#menu">
                                <li>
                                    <a asp-controller="Productos" asp-action="Index" class="nav-link px-0"><span class="d-none d-sm-inline"></span>  Productos </a>
                                </li>
                                <li>
                                    <a asp-controller="Servicios" asp-action="Index" class="nav-link px-0"><span class="d-none d-sm-inline"></span> Servicios </a>
                                </li>
                                <li>
                                    <a asp-controller="Sucursales" asp-action="TablaSucursales" class="nav-link px-0"><span class="d-none d-sm-inline"></span> Sucursales </a>
                                </li>
                                <li>
                                    <a asp-controller="Horarios" asp-action="Index" class="nav-link px-0"><span class="d-none d-sm-inline"></span> Horarios </a>
                                </li>
                                <li>
                                    <a asp-controller="Agenda" asp-action="Index" class="nav-link px-0"><span class="d-none d-sm-inline"></span> Agenda </a>
                                </li>
                            </ul>
                        </li>

                        <li>
                            <a href="#submenuProcesos" data-bs-toggle="collapse" class="nav-link text-white px-0 align-middle">
                                <i class="fs-4 fs-4 bi-gear-fill"></i> <span class="ms-1 d-none d-sm-inline">Proceso</span>
                            </a>
                            <ul class="collapse show nav flex-column ms-1" id="submenuProcesos" data-bs-parent="#menu">
                                <li class="w-100">
                                    <a asp-controller="Sucursales" asp-action="Index" class="nav-link px-0"><span class="d-none d-sm-inline"></span> Reservas </a>
                                </li>
                                <li>
                                    <a asp-controller="Factura" asp-action="Index" class="nav-link px-0"><span class="d-none d-sm-inline"></span> Facturas </a>
                                </li>
                            </ul>
                        </li>

                        @if (User.IsInRole("Administrador") == true)
                        {
                            <li>
                                <a href="#submenuSeguridad" data-bs-toggle="collapse" class="nav-link text-white px-0 align-middle">
                                    <i class="fs-4 fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Seguridad</span>
                                </a>
                                <ul class="collapse show nav flex-column ms-1" id="submenuSeguridad" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a asp-controller="Usuarios" asp-action="Index" class="nav-link px-0"><span class="d-none d-sm-inline"></span> Usuarios </a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <hr>
                    <div class="dropdown pb-4">
                        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                            @* <img class="rounded-circle mx-2 mt-1" src="~/images/profile.png" alt=@User.Identity!.Name width="32px" height="32px" /> *@
                            <span class="d-none d-sm-inline mx-1">Usuario :  @User.Identity!.Name</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                            <li>
                                <a asp-controller="Login" asp-action="Index" class="dropdown-item"><span class="d-none d-sm-inline"></span>Salir</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <!-- Contenido principal ajustado -->
            <div class="col content-area">
                <div class="container">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Ajax unobtrusive-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.js" integrity="sha512-f04GBpoqEZhbyjlRTuXeg8FIHDb+xfCJ0LVdqiN1fEl5B3jz3Z0SPe9IxDumOVdTeeXmKMcMJhb26VuGf1Laqw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- SweetAlert-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.4/dist/sweetalert2.all.min.js"></script>

    <!-- Notificaciones con SweetAlert -->
    @if (ViewBag.NotificationMessage != null)
    {
        <script>
            @Html.Raw(@ViewBag.NotificationMessage);
        </script>
    }

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TallerMotos/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
   <!-- <link href="css/styles.css" rel="stylesheet" /> -->
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a href="@Url.Action("Index", "Home")" class="navbar-brand ps-3">
            <span class="fs-5 d-none d-sm-inline"> MS BEICHA</span>
            </a>

                <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="@Url.Action("Index","Dashboard")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Layouts
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Login</a>
                                        <a class="nav-link" href="register.html">Register</a>
                                        <a class="nav-link" href="password.html">Forgot Password</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="401.html">401 Page</a>
                                        <a class="nav-link" href="404.html">404 Page</a>
                                        <a class="nav-link" href="500.html">500 Page</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tables
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
           <!-- <main>
                <div class="container-fluid px-4">
                    <h1 class="mt-4">Static Navigation</h1>
                    <ol class="breadcrumb mb-4">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active">Static Navigation</li>
                    </ol>
                    <div class="card mb-4">
                        <div class="card-body">
                            <p class="mb-0">
                                This page is an example of using static navigation. By removing the
                                <code>.sb-nav-fixed</code>
                                class from the
                                <code>body</code>
                                , the top navigation and side navigation will become static on scroll. Scroll down this page to see an example.
                            </p>
                        </div>
                    </div>
                    <div style="height: 100vh"></div>
                    <div class="card mb-4"><div class="card-body">When scrolling, the navigation stays at the top of the page. This is the end of the static navigation demo.</div></div>
                </div>
             </main> -->
            <div class="col py-3">
                <div class="container">
                    <main role="main" class="pb-3">
        @RenderBody()
                    </main>
                </div>
            </div>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
           
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="js/scripts.js"></script>
</body>
</html>